In [19]:
import pandas as pd
import numpy as np
from datetime import datetime

# Sample DataFrame creation
data = {
    'date': pd.date_range(start='2022-05-17 17:06:40', periods=4, freq='H')
}
dates = pd.DataFrame(data)

# time_features function definition
def time_features(dates, timeenc=0, freq='h'):
    if timeenc == 0:
        dates['year'] = dates.date.apply(lambda row: row.year)
        dates['month'] = dates.date.apply(lambda row: row.month)
        dates['day'] = dates.date.apply(lambda row: row.day)
        dates['weekday'] = dates.date.apply(lambda row: row.weekday())
        dates['hour'] = dates.date.apply(lambda row: row.hour)
        dates['minute'] = dates.date.apply(lambda row: row.minute)
        #dates['minute'] = dates['minute'].map(lambda x: x // 15)
        freq_map = {
            'y': ['year'], 'm': ['month'], 'w': ['month'], 'd': ['month', 'day', 'weekday'],
            'b': ['month', 'day', 'weekday'], 'h': ['month', 'day', 'weekday', 'hour'],
            't': ['month', 'day', 'weekday', 'hour', 'minute'],
        }
        return dates[freq_map[freq.lower()]].values
    else:
        # For demonstration, just returning an empty array for timeenc=1
        # Implement normalization as needed
        return np.array([])

# Testing the function
print("Testing with freq='t' and timeenc=0:")
print(time_features(dates, timeenc=0, freq='t'))

print("\nTesting with freq='d' and timeenc=0:")
print(time_features(dates, timeenc=0, freq='d'))

# Example for timeenc=1 would require implementing the normalization part


Testing with freq='t' and timeenc=0:
[[ 5 17  1 17  6]
 [ 5 17  1 18  6]
 [ 5 17  1 19  6]
 [ 5 17  1 20  6]]

Testing with freq='d' and timeenc=0:
[[ 5 17  1]
 [ 5 17  1]
 [ 5 17  1]
 [ 5 17  1]]


C:\Users\lia68085\AppData\Local\Temp\ipykernel_6120\3924161930.py:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  'date': pd.date_range(start='2022-05-17 17:06:40', periods=4, freq='H')


In [20]:
dates

date  year  month  day  weekday  hour  minute
0 2022-05-17 17:06:40  2022      5   17        1    17       6
1 2022-05-17 18:06:40  2022      5   17        1    18       6
2 2022-05-17 19:06:40  2022      5   17        1    19       6
3 2022-05-17 20:06:40  2022      5   17        1    20       6

In [12]:
from datetime import datetime

# Assuming your timestamp is in seconds (Unix time)
timestamp = 1652800000

# Convert to a datetime object
dt_object = datetime.fromtimestamp(timestamp)

# Print the datetime in a readable format
print(dt_object.strftime('%Y-%m-%d %H:%M:%S'))


2022-05-17 17:06:40
