In [19]:
import pandas as pd
import numpy as np
from datetime import datetime

# Sample DataFrame creation
data = {
    'date': pd.date_range(start='2022-05-17 17:06:40', periods=4, freq='H')
}
dates = pd.DataFrame(data)

# time_features function definition
def time_features(dates, timeenc=0, freq='h'):
    if timeenc == 0:
        dates['year'] = dates.date.apply(lambda row: row.year)
        dates['month'] = dates.date.apply(lambda row: row.month)
        dates['day'] = dates.date.apply(lambda row: row.day)
        dates['weekday'] = dates.date.apply(lambda row: row.weekday())
        dates['hour'] = dates.date.apply(lambda row: row.hour)
        dates['minute'] = dates.date.apply(lambda row: row.minute)
        #dates['minute'] = dates['minute'].map(lambda x: x // 15)
        freq_map = {
            'y': ['year'], 'm': ['month'], 'w': ['month'], 'd': ['month', 'day', 'weekday'],
            'b': ['month', 'day', 'weekday'], 'h': ['month', 'day', 'weekday', 'hour'],
            't': ['month', 'day', 'weekday', 'hour', 'minute'],
        }
        return dates[freq_map[freq.lower()]].values
    else:
        # For demonstration, just returning an empty array for timeenc=1
        # Implement normalization as needed
        return np.array([])

# Testing the function
print("Testing with freq='t' and timeenc=0:")
print(time_features(dates, timeenc=0, freq='t'))

print("\nTesting with freq='d' and timeenc=0:")
print(time_features(dates, timeenc=0, freq='d'))

# Example for timeenc=1 would require implementing the normalization part


Testing with freq='t' and timeenc=0:
[[ 5 17  1 17  6]
 [ 5 17  1 18  6]
 [ 5 17  1 19  6]
 [ 5 17  1 20  6]]

Testing with freq='d' and timeenc=0:
[[ 5 17  1]
 [ 5 17  1]
 [ 5 17  1]
 [ 5 17  1]]


C:\Users\lia68085\AppData\Local\Temp\ipykernel_6120\3924161930.py:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  'date': pd.date_range(start='2022-05-17 17:06:40', periods=4, freq='H')


In [20]:
dates

date  year  month  day  weekday  hour  minute
0 2022-05-17 17:06:40  2022      5   17        1    17       6
1 2022-05-17 18:06:40  2022      5   17        1    18       6
2 2022-05-17 19:06:40  2022      5   17        1    19       6
3 2022-05-17 20:06:40  2022      5   17        1    20       6

In [12]:
from datetime import datetime

# Assuming your timestamp is in seconds (Unix time)
timestamp = 1652800000

# Convert to a datetime object
dt_object = datetime.fromtimestamp(timestamp)

# Print the datetime in a readable format
print(dt_object.strftime('%Y-%m-%d %H:%M:%S'))


2022-05-17 17:06:40


In [2]:
import pandas as pd
import numpy as np

path=r'D:\studydata\Masterarbeit\Data\all_second_data.csv'
data = pd.read_csv(path)


In [ ]:
data.Timestamp = pd.to_datetime(data.Timestamp, unit='s')


In [3]:
# how many days are in the data

data.Date = pd.to_datetime(data.Date)
data.Date.tail()
data.Date.head()
print(data.Date.min())
data.Date.max()
# how many days are in the data


2020-11-04 11:40:00


Timestamp('2020-11-21 05:18:35')

In [4]:
data.Date.max()-data.Date.min()
# capture the time of the day
days=np.unique(data.Date.dt.day)
days


array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21], dtype=int64)

In [5]:

lengths_days={}
for x in days:
    lengths_days[f'11-{x}']=len(data[data.Date.dt.day==x])
    print(f'11-{x}',len(data[data.Date.dt.day==x]))
    print('-------------------------')
# create a 

11-4 44400
-------------------------
11-5 86400
-------------------------
11-6 86400
-------------------------
11-7 86400
-------------------------
11-8 86400
-------------------------
11-9 86400
-------------------------
11-10 86400
-------------------------
11-11 86400
-------------------------
11-12 86400
-------------------------
11-13 86400
-------------------------
11-14 86400
-------------------------
11-15 86400
-------------------------
11-16 86400
-------------------------
11-17 86400
-------------------------
11-18 86400
-------------------------
11-19 86400
-------------------------
11-20 86400
-------------------------
11-21 19116
-------------------------


In [8]:
lengths_days
# save this dictionary to a csv file
df=pd.DataFrame(lengths_days.items(),columns=['day','length'])
df.to_csv('lengths_days.csv',index=False)
df.to_excel('lengths_days.xlsx',index=False)

In [23]:
len(data)

1445916